export const COPY = {
  header: {
    title: 'Dado Interledger',
    tagline: 'Micro-pagos ILP en tiempo real',
    connectWallet: 'Conectar Billetera',
    connected: 'Conectado',
    grantRemaining: 'Saldo Disponible',
    txHistory: 'Historial',
    leaveRoom: 'Abandonar Sala',
  },
  lobby: {
    badge: 'Sala de Juego en Vivo',
    title: 'Mesa de Dados Interledger',
    subtitle: 'Ingresa tu Puntero de Pago (Payment Pointer) y autoriza un permiso de micro-pagos para ingresar a la sala en tiempo real.',
    pointerLabel: 'Puntero de Pago ILP (Payment Pointer)',
    pointerPlaceholder: '$ilp.ejemplo/tu-usuario',
    quickFillTitle: 'Punteros de demostración:',
    grantLabel: 'Autorización de Permiso Inicial (USD)',
    grantHelpText: 'Cada apuesta descontará automáticamente $0.10 USD de este permiso sin fricción.',
    enterBtn: 'Autorizar e Ingresar a la Sala',
    enteringBtn: 'Autorizando e Ingresando...',
    rule1: 'Rondas de 30 segundos con tiradas de dados 3D en vivo.',
    rule2: 'Apuesta fija de $0.10 USD por tirada (máximo 1 apuesta por ronda).',
    rule3: 'Comisión del 10% para la casa en rondas ganadoras; 90% repartido entre acertantes.',
    rule4: 'Si nadie acierta, el 100% del pozo se acumula para la siguiente ronda.',
    rule5: 'Si nadie gana y todos abandonan la sala, el pozo queda para la casa.',
  },
  walletModal: {
    title: 'Conectar Billetera Interledger',
    subtitle: 'Ingresa tu Puntero de Pago (Payment Pointer) y autoriza un permiso de micro-pagos para jugar.',
    pointerLabel: 'Puntero de Pago (ILP)',
    pointerPlaceholder: '$ilp.ejemplo/tu-usuario',
    quickFillTitle: 'Punteros de prueba sugeridos:',
    grantLimitLabel: 'Límite de Permiso a Autorizar (USD)',
    grantHelpText: 'Este permiso autorizará micro-pagos automáticos de $0.10 USD cada vez que apuestes, sin pedir confirmaciones adicionales por cada ronda.',
    authorizeBtn: 'Autorizar y Conectar',
    authorizing: 'Autorizando Permiso...',
    cancelBtn: 'Cancelar',
  },
  game: {
    phaseBetting: '¡Haz tu predicción!',
    phaseRolling: '¡Tirando los dados!',
    phaseResolving: 'Calculando ganadores...',
    phaseSettled: 'Ronda finalizada',
    roundNumber: 'Ronda',
    fixedBetNotice: 'Apuesta fija: $0.10 USD por tirada',
    currentRoundPool: 'Pozo de esta Ronda',
    accumulatedJackpot: 'Pozo Acumulado (Jackpot)',
    totalPrizePool: 'Pozo Total en Juego',
    placeBetBtn: 'Apostar $0.10 USD',
    authorizingBet: 'Procesando micro-pago...',
    betPlacedBadge: 'Tu apuesta:',
    alreadyBetNotice: 'Ya tienes una apuesta activa en esta ronda',
    connectToBet: 'Conecta tu billetera para apostar',
    timeLeft: 'Tiempo restante',
    diceResult: 'Resultado de los Dados',
    sumResult: 'Suma:',
    singleGuessNotice: 'Máximo 1 predicción por jugador en cada ronda de 30s.',
    pickNumberPrompt: 'Selecciona una suma entre 2 y 12:',
    livePlayersTitle: 'Apuestas en la Ronda',
    noBetsYet: 'Aún no hay apuestas registradas en esta ronda. ¡Sé el primero!',
    recentRoundsTitle: 'Últimas Rondas',
    multiplierLabel: 'Multiplicador',
    probabilityLabel: 'Probabilidad',
  },
  disclaimer: {
    title: 'Reglas de la Sala & Comisión de la Casa',
    houseFee: 'La casa retiene una comisión del 10% del pozo total en cada ronda con ganadores.',
    rolloverRule: 'Si ningún jugador acierta el resultado, el 100% del pozo pasa acumulado a la siguiente ronda.',
    abandonedRoomRule: 'Aviso importante: Si nadie gana y todos los jugadores abandonan la sala, el pozo acumulado queda en posesión de la casa.',
  },
  outcomes: {
    victoryTitle: '¡Felicidades, ganaste!',
    victorySubtitle: 'Acertaste la suma de los dados con tu predicción.',
    lossTitle: 'No hubo suerte esta vez',
    lossSubtitle: 'Tu predicción no coincidió con el resultado de los dados.',
    noWinnersTitle: '¡Nadie acertó en esta ronda!',
    noWinnersSubtitle: '¡El pozo total pasa al Pozo Acumulado de la siguiente ronda!',
    grossPool: 'Pozo Total:',
    houseTake: 'Comisión de la casa (10%):',
    netPrize: 'Premio neto a ganadores (90%):',
    yourShare: 'Tu premio acreditado:',
    winningNumber: 'Número Ganador:',
    diceDetail: 'Dados:',
    winnersList: 'Ganadores:',
    nextRoundCountdown: 'La siguiente ronda comienza en segundos...',
    closeBtn: 'Cerrar',
  },
  toasts: {
    grantSuccess: 'Permiso Interledger autorizado exitosamente por',
    walletDisconnected: 'Billetera desconectada.',
    betSuccess: 'Micro-pago de $0.10 procesado. ¡Apuesta confirmada en el número',
    betFailed: 'No se pudo procesar el micro-pago. Por favor intenta de nuevo.',
    grantDepleted: 'El saldo del permiso se ha agotado ($0.00). Autoriza un nuevo permiso para continuar.',
    roundClosed: 'Tiempo de apuestas cerrado. Espera a la siguiente ronda.',
    winCelebration: '¡Ganaste en la ronda! Premio de',
  },
  txHistory: {
    title: 'Historial de Micro-pagos ILP',
    subtitle: 'Registro de transferencias del permiso activo',
    empty: 'No hay transacciones registradas aún.',
    typeBet: 'Apuesta',
    typePayout: 'Premio Ganado',
    typeGrant: 'Permiso Inicial',
    statusSuccess: 'Completado',
    statusFailed: 'Fallido',
    txHash: 'Comprobante:',
    closeBtn: 'Cerrar',
  },
};
